development:
  adapter: postgresql
  encoding: unicode
  database: election_development
  pool: 5
  host: localhost
  username: hui
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: election_test
  pool: 5
  host: localhost
  username: hui
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: election_production
  pool: 5
  username: hui
  password: password
